export const MEMBER = 'MEMBER';
export const COACH = 'COACH';
export const MANAGER = 'MANAGER';
export const ADMIN = 'ADMIN';
export const GOOGLE = 'google.com';
export const PHONE = 'phone';
export const PASSWORD = 'password';
export const APPLE = 'apple.com';
export const AUTHPROVIDERS = [GOOGLE, PHONE, PASSWORD, APPLE];
